#! /bin/bash

LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse ${1:-'@{u}'})
BASE=$(git merge-base @ ${1:-'@{u}'})

if [ $LOCAL = $REMOTE ]; then
    echo 0
elif [ $LOCAL = $BASE ]; then
    echo 1
elif [ $REMOTE = $BASE ]; then
    echo 0
else
    echo 0
fi
